#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 16 09:15:54 -05 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_fpu_top_mul_simple_behav -key {Behavioral:sim_1:Functional:tb_fpu_top_mul_simple} -tclbatch tb_fpu_top_mul_simple.tcl -view /tools/Xilinx/2025.1/Vivado/bin/ALU_FINAL/tb_fpu_top_mul_simple_behav.wcfg -view /tools/Xilinx/2025.1/Vivado/bin/ALU_FINAL/tb_fpu_top_min_behav.wcfg -log simulate.log"
xsim tb_fpu_top_mul_simple_behav -key {Behavioral:sim_1:Functional:tb_fpu_top_mul_simple} -tclbatch tb_fpu_top_mul_simple.tcl -view /tools/Xilinx/2025.1/Vivado/bin/ALU_FINAL/tb_fpu_top_mul_simple_behav.wcfg -view /tools/Xilinx/2025.1/Vivado/bin/ALU_FINAL/tb_fpu_top_min_behav.wcfg -log simulate.log

